delete from prob_migration;
commit;
delete from miwtpersonne; 
commit;
delete from miwengabn;
commit;
delete from miwabn;
commit;
commit;
delete from miwtpdl;
commit;
delete from MIWTPROPRIETAIRE;
commit;
delete from MIWTHISTOPAYEUR;  
commit;
delete from miwtsite;
commit;
delete from miwabn;
commit;
delete from miwtbra;
commit;
delete from miwttournee;
commit;
delete from  MIWTHISTOCPT;
commit;
delete from miwtcompteur;
commit;
delete from miwtadr a where a.madr_ref<>'0';
commit;
delete from miwtreleve_histocpt;
commit;
delete from miwtreleve;
commit;
delete from miwtrelevet;
commit;
delete from miwtreleve_gc;
commit;
delete from miwtreleve_gc_1;
commit;
delete from MIWTFAIRESUIVRE;
commit;
delete from MIWTRIB;
commit;
delete from miwtfactureentete;
commit;
delete from miwtfactureligne;
commit;
delete from BRANCHEMENT_RES ;
commit;
delete from BRANCHEMENT_RES_MAX ;
commit;
