prompt Importing table miworganization...
set feedback off
set define off
insert into miworganization (MORGA_SOURCE, MORGA_REFORGA, MORGA_LIBELLE, MORGA_POSTECOMPTABLE, MORGA_NNE, MORGA_CENTRE, MORGA_DOCUMENT, MORGA_LOPFMT, MORGA_BANQUE, MORGA_NUMCOMPTE, MORGA_FLUX, MORGA_NNE_REMBOURS, MORGA_LIGNEOPTIQUE, MORGA_DIVERS, MORGA_RMH, MORGA_BANKFMT, MORGA_ICS, MORGA_BIC)
values ('DIST01', '01', null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null);

insert into miworganization (MORGA_SOURCE, MORGA_REFORGA, MORGA_LIBELLE, MORGA_POSTECOMPTABLE, MORGA_NNE, MORGA_CENTRE, MORGA_DOCUMENT, MORGA_LOPFMT, MORGA_BANQUE, MORGA_NUMCOMPTE, MORGA_FLUX, MORGA_NNE_REMBOURS, MORGA_LIGNEOPTIQUE, MORGA_DIVERS, MORGA_RMH, MORGA_BANKFMT, MORGA_ICS, MORGA_BIC)
values ('DIST03', '03', null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null);

insert into miworganization (MORGA_SOURCE, MORGA_REFORGA, MORGA_LIBELLE, MORGA_POSTECOMPTABLE, MORGA_NNE, MORGA_CENTRE, MORGA_DOCUMENT, MORGA_LOPFMT, MORGA_BANQUE, MORGA_NUMCOMPTE, MORGA_FLUX, MORGA_NNE_REMBOURS, MORGA_LIGNEOPTIQUE, MORGA_DIVERS, MORGA_RMH, MORGA_BANKFMT, MORGA_ICS, MORGA_BIC)
values ('DIST04', '04', null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null);

insert into miworganization (MORGA_SOURCE, MORGA_REFORGA, MORGA_LIBELLE, MORGA_POSTECOMPTABLE, MORGA_NNE, MORGA_CENTRE, MORGA_DOCUMENT, MORGA_LOPFMT, MORGA_BANQUE, MORGA_NUMCOMPTE, MORGA_FLUX, MORGA_NNE_REMBOURS, MORGA_LIGNEOPTIQUE, MORGA_DIVERS, MORGA_RMH, MORGA_BANKFMT, MORGA_ICS, MORGA_BIC)
values ('DIST05', '05', null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null);

insert into miworganization (MORGA_SOURCE, MORGA_REFORGA, MORGA_LIBELLE, MORGA_POSTECOMPTABLE, MORGA_NNE, MORGA_CENTRE, MORGA_DOCUMENT, MORGA_LOPFMT, MORGA_BANQUE, MORGA_NUMCOMPTE, MORGA_FLUX, MORGA_NNE_REMBOURS, MORGA_LIGNEOPTIQUE, MORGA_DIVERS, MORGA_RMH, MORGA_BANKFMT, MORGA_ICS, MORGA_BIC)
values ('DIST06', '06', null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null);

insert into miworganization (MORGA_SOURCE, MORGA_REFORGA, MORGA_LIBELLE, MORGA_POSTECOMPTABLE, MORGA_NNE, MORGA_CENTRE, MORGA_DOCUMENT, MORGA_LOPFMT, MORGA_BANQUE, MORGA_NUMCOMPTE, MORGA_FLUX, MORGA_NNE_REMBOURS, MORGA_LIGNEOPTIQUE, MORGA_DIVERS, MORGA_RMH, MORGA_BANKFMT, MORGA_ICS, MORGA_BIC)
values ('DIST07', '07', null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null);

insert into miworganization (MORGA_SOURCE, MORGA_REFORGA, MORGA_LIBELLE, MORGA_POSTECOMPTABLE, MORGA_NNE, MORGA_CENTRE, MORGA_DOCUMENT, MORGA_LOPFMT, MORGA_BANQUE, MORGA_NUMCOMPTE, MORGA_FLUX, MORGA_NNE_REMBOURS, MORGA_LIGNEOPTIQUE, MORGA_DIVERS, MORGA_RMH, MORGA_BANKFMT, MORGA_ICS, MORGA_BIC)
values ('DIST08', '08', null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null);

insert into miworganization (MORGA_SOURCE, MORGA_REFORGA, MORGA_LIBELLE, MORGA_POSTECOMPTABLE, MORGA_NNE, MORGA_CENTRE, MORGA_DOCUMENT, MORGA_LOPFMT, MORGA_BANQUE, MORGA_NUMCOMPTE, MORGA_FLUX, MORGA_NNE_REMBOURS, MORGA_LIGNEOPTIQUE, MORGA_DIVERS, MORGA_RMH, MORGA_BANKFMT, MORGA_ICS, MORGA_BIC)
values ('DIST09', '09', null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null);

insert into miworganization (MORGA_SOURCE, MORGA_REFORGA, MORGA_LIBELLE, MORGA_POSTECOMPTABLE, MORGA_NNE, MORGA_CENTRE, MORGA_DOCUMENT, MORGA_LOPFMT, MORGA_BANQUE, MORGA_NUMCOMPTE, MORGA_FLUX, MORGA_NNE_REMBOURS, MORGA_LIGNEOPTIQUE, MORGA_DIVERS, MORGA_RMH, MORGA_BANKFMT, MORGA_ICS, MORGA_BIC)
values ('DIST13', '13', null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null);

insert into miworganization (MORGA_SOURCE, MORGA_REFORGA, MORGA_LIBELLE, MORGA_POSTECOMPTABLE, MORGA_NNE, MORGA_CENTRE, MORGA_DOCUMENT, MORGA_LOPFMT, MORGA_BANQUE, MORGA_NUMCOMPTE, MORGA_FLUX, MORGA_NNE_REMBOURS, MORGA_LIGNEOPTIQUE, MORGA_DIVERS, MORGA_RMH, MORGA_BANKFMT, MORGA_ICS, MORGA_BIC)
values ('DIST14', '14', null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null);

insert into miworganization (MORGA_SOURCE, MORGA_REFORGA, MORGA_LIBELLE, MORGA_POSTECOMPTABLE, MORGA_NNE, MORGA_CENTRE, MORGA_DOCUMENT, MORGA_LOPFMT, MORGA_BANQUE, MORGA_NUMCOMPTE, MORGA_FLUX, MORGA_NNE_REMBOURS, MORGA_LIGNEOPTIQUE, MORGA_DIVERS, MORGA_RMH, MORGA_BANKFMT, MORGA_ICS, MORGA_BIC)
values ('DIST15', '15', null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null);

insert into miworganization (MORGA_SOURCE, MORGA_REFORGA, MORGA_LIBELLE, MORGA_POSTECOMPTABLE, MORGA_NNE, MORGA_CENTRE, MORGA_DOCUMENT, MORGA_LOPFMT, MORGA_BANQUE, MORGA_NUMCOMPTE, MORGA_FLUX, MORGA_NNE_REMBOURS, MORGA_LIGNEOPTIQUE, MORGA_DIVERS, MORGA_RMH, MORGA_BANKFMT, MORGA_ICS, MORGA_BIC)
values ('DIST16', '16', null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null);

insert into miworganization (MORGA_SOURCE, MORGA_REFORGA, MORGA_LIBELLE, MORGA_POSTECOMPTABLE, MORGA_NNE, MORGA_CENTRE, MORGA_DOCUMENT, MORGA_LOPFMT, MORGA_BANQUE, MORGA_NUMCOMPTE, MORGA_FLUX, MORGA_NNE_REMBOURS, MORGA_LIGNEOPTIQUE, MORGA_DIVERS, MORGA_RMH, MORGA_BANKFMT, MORGA_ICS, MORGA_BIC)
values ('DIST17', '17', null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null);

insert into miworganization (MORGA_SOURCE, MORGA_REFORGA, MORGA_LIBELLE, MORGA_POSTECOMPTABLE, MORGA_NNE, MORGA_CENTRE, MORGA_DOCUMENT, MORGA_LOPFMT, MORGA_BANQUE, MORGA_NUMCOMPTE, MORGA_FLUX, MORGA_NNE_REMBOURS, MORGA_LIGNEOPTIQUE, MORGA_DIVERS, MORGA_RMH, MORGA_BANKFMT, MORGA_ICS, MORGA_BIC)
values ('DIST19', '19', null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null);

insert into miworganization (MORGA_SOURCE, MORGA_REFORGA, MORGA_LIBELLE, MORGA_POSTECOMPTABLE, MORGA_NNE, MORGA_CENTRE, MORGA_DOCUMENT, MORGA_LOPFMT, MORGA_BANQUE, MORGA_NUMCOMPTE, MORGA_FLUX, MORGA_NNE_REMBOURS, MORGA_LIGNEOPTIQUE, MORGA_DIVERS, MORGA_RMH, MORGA_BANKFMT, MORGA_ICS, MORGA_BIC)
values ('DIST20', '20', null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null);

insert into miworganization (MORGA_SOURCE, MORGA_REFORGA, MORGA_LIBELLE, MORGA_POSTECOMPTABLE, MORGA_NNE, MORGA_CENTRE, MORGA_DOCUMENT, MORGA_LOPFMT, MORGA_BANQUE, MORGA_NUMCOMPTE, MORGA_FLUX, MORGA_NNE_REMBOURS, MORGA_LIGNEOPTIQUE, MORGA_DIVERS, MORGA_RMH, MORGA_BANKFMT, MORGA_ICS, MORGA_BIC)
values ('DIST21', '21', null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null);

insert into miworganization (MORGA_SOURCE, MORGA_REFORGA, MORGA_LIBELLE, MORGA_POSTECOMPTABLE, MORGA_NNE, MORGA_CENTRE, MORGA_DOCUMENT, MORGA_LOPFMT, MORGA_BANQUE, MORGA_NUMCOMPTE, MORGA_FLUX, MORGA_NNE_REMBOURS, MORGA_LIGNEOPTIQUE, MORGA_DIVERS, MORGA_RMH, MORGA_BANKFMT, MORGA_ICS, MORGA_BIC)
values ('DIST22', '22', null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null);

insert into miworganization (MORGA_SOURCE, MORGA_REFORGA, MORGA_LIBELLE, MORGA_POSTECOMPTABLE, MORGA_NNE, MORGA_CENTRE, MORGA_DOCUMENT, MORGA_LOPFMT, MORGA_BANQUE, MORGA_NUMCOMPTE, MORGA_FLUX, MORGA_NNE_REMBOURS, MORGA_LIGNEOPTIQUE, MORGA_DIVERS, MORGA_RMH, MORGA_BANKFMT, MORGA_ICS, MORGA_BIC)
values ('DIST24', '24', null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null);

insert into miworganization (MORGA_SOURCE, MORGA_REFORGA, MORGA_LIBELLE, MORGA_POSTECOMPTABLE, MORGA_NNE, MORGA_CENTRE, MORGA_DOCUMENT, MORGA_LOPFMT, MORGA_BANQUE, MORGA_NUMCOMPTE, MORGA_FLUX, MORGA_NNE_REMBOURS, MORGA_LIGNEOPTIQUE, MORGA_DIVERS, MORGA_RMH, MORGA_BANKFMT, MORGA_ICS, MORGA_BIC)
values ('DIST25', '25', null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null);

insert into miworganization (MORGA_SOURCE, MORGA_REFORGA, MORGA_LIBELLE, MORGA_POSTECOMPTABLE, MORGA_NNE, MORGA_CENTRE, MORGA_DOCUMENT, MORGA_LOPFMT, MORGA_BANQUE, MORGA_NUMCOMPTE, MORGA_FLUX, MORGA_NNE_REMBOURS, MORGA_LIGNEOPTIQUE, MORGA_DIVERS, MORGA_RMH, MORGA_BANKFMT, MORGA_ICS, MORGA_BIC)
values ('DIST26', '26', null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null);

insert into miworganization (MORGA_SOURCE, MORGA_REFORGA, MORGA_LIBELLE, MORGA_POSTECOMPTABLE, MORGA_NNE, MORGA_CENTRE, MORGA_DOCUMENT, MORGA_LOPFMT, MORGA_BANQUE, MORGA_NUMCOMPTE, MORGA_FLUX, MORGA_NNE_REMBOURS, MORGA_LIGNEOPTIQUE, MORGA_DIVERS, MORGA_RMH, MORGA_BANKFMT, MORGA_ICS, MORGA_BIC)
values ('DIST27', '27', null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null);

insert into miworganization (MORGA_SOURCE, MORGA_REFORGA, MORGA_LIBELLE, MORGA_POSTECOMPTABLE, MORGA_NNE, MORGA_CENTRE, MORGA_DOCUMENT, MORGA_LOPFMT, MORGA_BANQUE, MORGA_NUMCOMPTE, MORGA_FLUX, MORGA_NNE_REMBOURS, MORGA_LIGNEOPTIQUE, MORGA_DIVERS, MORGA_RMH, MORGA_BANKFMT, MORGA_ICS, MORGA_BIC)
values ('DIST28', '28', null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null);

insert into miworganization (MORGA_SOURCE, MORGA_REFORGA, MORGA_LIBELLE, MORGA_POSTECOMPTABLE, MORGA_NNE, MORGA_CENTRE, MORGA_DOCUMENT, MORGA_LOPFMT, MORGA_BANQUE, MORGA_NUMCOMPTE, MORGA_FLUX, MORGA_NNE_REMBOURS, MORGA_LIGNEOPTIQUE, MORGA_DIVERS, MORGA_RMH, MORGA_BANKFMT, MORGA_ICS, MORGA_BIC)
values ('DIST29', '29', null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null);

insert into miworganization (MORGA_SOURCE, MORGA_REFORGA, MORGA_LIBELLE, MORGA_POSTECOMPTABLE, MORGA_NNE, MORGA_CENTRE, MORGA_DOCUMENT, MORGA_LOPFMT, MORGA_BANQUE, MORGA_NUMCOMPTE, MORGA_FLUX, MORGA_NNE_REMBOURS, MORGA_LIGNEOPTIQUE, MORGA_DIVERS, MORGA_RMH, MORGA_BANKFMT, MORGA_ICS, MORGA_BIC)
values ('DIST31', '31', null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null);

insert into miworganization (MORGA_SOURCE, MORGA_REFORGA, MORGA_LIBELLE, MORGA_POSTECOMPTABLE, MORGA_NNE, MORGA_CENTRE, MORGA_DOCUMENT, MORGA_LOPFMT, MORGA_BANQUE, MORGA_NUMCOMPTE, MORGA_FLUX, MORGA_NNE_REMBOURS, MORGA_LIGNEOPTIQUE, MORGA_DIVERS, MORGA_RMH, MORGA_BANKFMT, MORGA_ICS, MORGA_BIC)
values ('DIST32', '32', null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null);

insert into miworganization (MORGA_SOURCE, MORGA_REFORGA, MORGA_LIBELLE, MORGA_POSTECOMPTABLE, MORGA_NNE, MORGA_CENTRE, MORGA_DOCUMENT, MORGA_LOPFMT, MORGA_BANQUE, MORGA_NUMCOMPTE, MORGA_FLUX, MORGA_NNE_REMBOURS, MORGA_LIGNEOPTIQUE, MORGA_DIVERS, MORGA_RMH, MORGA_BANKFMT, MORGA_ICS, MORGA_BIC)
values ('DIST33', '33', null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null);

insert into miworganization (MORGA_SOURCE, MORGA_REFORGA, MORGA_LIBELLE, MORGA_POSTECOMPTABLE, MORGA_NNE, MORGA_CENTRE, MORGA_DOCUMENT, MORGA_LOPFMT, MORGA_BANQUE, MORGA_NUMCOMPTE, MORGA_FLUX, MORGA_NNE_REMBOURS, MORGA_LIGNEOPTIQUE, MORGA_DIVERS, MORGA_RMH, MORGA_BANKFMT, MORGA_ICS, MORGA_BIC)
values ('DIST34', '34', null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null);

 
insert into miworganization (MORGA_SOURCE, MORGA_REFORGA, MORGA_LIBELLE, MORGA_POSTECOMPTABLE, MORGA_NNE, MORGA_CENTRE, MORGA_DOCUMENT, MORGA_LOPFMT, MORGA_BANQUE, MORGA_NUMCOMPTE, MORGA_FLUX, MORGA_NNE_REMBOURS, MORGA_LIGNEOPTIQUE, MORGA_DIVERS, MORGA_RMH, MORGA_BANKFMT, MORGA_ICS, MORGA_BIC)
values ('DIST36', '36', null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null);

insert into miworganization (MORGA_SOURCE, MORGA_REFORGA, MORGA_LIBELLE, MORGA_POSTECOMPTABLE, MORGA_NNE, MORGA_CENTRE, MORGA_DOCUMENT, MORGA_LOPFMT, MORGA_BANQUE, MORGA_NUMCOMPTE, MORGA_FLUX, MORGA_NNE_REMBOURS, MORGA_LIGNEOPTIQUE, MORGA_DIVERS, MORGA_RMH, MORGA_BANKFMT, MORGA_ICS, MORGA_BIC)
values ('DIST37', '37', null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null);

 insert into miworganization (MORGA_SOURCE, MORGA_REFORGA, MORGA_LIBELLE, MORGA_POSTECOMPTABLE, MORGA_NNE, MORGA_CENTRE, MORGA_DOCUMENT, MORGA_LOPFMT, MORGA_BANQUE, MORGA_NUMCOMPTE, MORGA_FLUX, MORGA_NNE_REMBOURS, MORGA_LIGNEOPTIQUE, MORGA_DIVERS, MORGA_RMH, MORGA_BANKFMT, MORGA_ICS, MORGA_BIC)
values ('DIST42', '42', null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null);

insert into miworganization (MORGA_SOURCE, MORGA_REFORGA, MORGA_LIBELLE, MORGA_POSTECOMPTABLE, MORGA_NNE, MORGA_CENTRE, MORGA_DOCUMENT, MORGA_LOPFMT, MORGA_BANQUE, MORGA_NUMCOMPTE, MORGA_FLUX, MORGA_NNE_REMBOURS, MORGA_LIGNEOPTIQUE, MORGA_DIVERS, MORGA_RMH, MORGA_BANKFMT, MORGA_ICS, MORGA_BIC)
values ('DIST44', '44', null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null);

insert into miworganization (MORGA_SOURCE, MORGA_REFORGA, MORGA_LIBELLE, MORGA_POSTECOMPTABLE, MORGA_NNE, MORGA_CENTRE, MORGA_DOCUMENT, MORGA_LOPFMT, MORGA_BANQUE, MORGA_NUMCOMPTE, MORGA_FLUX, MORGA_NNE_REMBOURS, MORGA_LIGNEOPTIQUE, MORGA_DIVERS, MORGA_RMH, MORGA_BANKFMT, MORGA_ICS, MORGA_BIC)
values ('DIST45', '45', null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null);

insert into miworganization (MORGA_SOURCE, MORGA_REFORGA, MORGA_LIBELLE, MORGA_POSTECOMPTABLE, MORGA_NNE, MORGA_CENTRE, MORGA_DOCUMENT, MORGA_LOPFMT, MORGA_BANQUE, MORGA_NUMCOMPTE, MORGA_FLUX, MORGA_NNE_REMBOURS, MORGA_LIGNEOPTIQUE, MORGA_DIVERS, MORGA_RMH, MORGA_BANKFMT, MORGA_ICS, MORGA_BIC)
values ('DIST46', '46', null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null);

insert into miworganization (MORGA_SOURCE, MORGA_REFORGA, MORGA_LIBELLE, MORGA_POSTECOMPTABLE, MORGA_NNE, MORGA_CENTRE, MORGA_DOCUMENT, MORGA_LOPFMT, MORGA_BANQUE, MORGA_NUMCOMPTE, MORGA_FLUX, MORGA_NNE_REMBOURS, MORGA_LIGNEOPTIQUE, MORGA_DIVERS, MORGA_RMH, MORGA_BANKFMT, MORGA_ICS, MORGA_BIC)
values ('DIST48', '48', null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null);

insert into miworganization (MORGA_SOURCE, MORGA_REFORGA, MORGA_LIBELLE, MORGA_POSTECOMPTABLE, MORGA_NNE, MORGA_CENTRE, MORGA_DOCUMENT, MORGA_LOPFMT, MORGA_BANQUE, MORGA_NUMCOMPTE, MORGA_FLUX, MORGA_NNE_REMBOURS, MORGA_LIGNEOPTIQUE, MORGA_DIVERS, MORGA_RMH, MORGA_BANKFMT, MORGA_ICS, MORGA_BIC)
values ('DIST49', '49', null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null);


insert into miworganization (MORGA_SOURCE, MORGA_REFORGA, MORGA_LIBELLE, MORGA_POSTECOMPTABLE, MORGA_NNE, MORGA_CENTRE, MORGA_DOCUMENT, MORGA_LOPFMT, MORGA_BANQUE, MORGA_NUMCOMPTE, MORGA_FLUX, MORGA_NNE_REMBOURS, MORGA_LIGNEOPTIQUE, MORGA_DIVERS, MORGA_RMH, MORGA_BANKFMT, MORGA_ICS, MORGA_BIC)
values ('DIST52', '52', null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null);

insert into miworganization (MORGA_SOURCE, MORGA_REFORGA, MORGA_LIBELLE, MORGA_POSTECOMPTABLE, MORGA_NNE, MORGA_CENTRE, MORGA_DOCUMENT, MORGA_LOPFMT, MORGA_BANQUE, MORGA_NUMCOMPTE, MORGA_FLUX, MORGA_NNE_REMBOURS, MORGA_LIGNEOPTIQUE, MORGA_DIVERS, MORGA_RMH, MORGA_BANKFMT, MORGA_ICS, MORGA_BIC)
values ('DIST53', '53', null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null);

insert into miworganization (MORGA_SOURCE, MORGA_REFORGA, MORGA_LIBELLE, MORGA_POSTECOMPTABLE, MORGA_NNE, MORGA_CENTRE, MORGA_DOCUMENT, MORGA_LOPFMT, MORGA_BANQUE, MORGA_NUMCOMPTE, MORGA_FLUX, MORGA_NNE_REMBOURS, MORGA_LIGNEOPTIQUE, MORGA_DIVERS, MORGA_RMH, MORGA_BANKFMT, MORGA_ICS, MORGA_BIC)
values ('DIST54', '54', null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null);

insert into miworganization (MORGA_SOURCE, MORGA_REFORGA, MORGA_LIBELLE, MORGA_POSTECOMPTABLE, MORGA_NNE, MORGA_CENTRE, MORGA_DOCUMENT, MORGA_LOPFMT, MORGA_BANQUE, MORGA_NUMCOMPTE, MORGA_FLUX, MORGA_NNE_REMBOURS, MORGA_LIGNEOPTIQUE, MORGA_DIVERS, MORGA_RMH, MORGA_BANKFMT, MORGA_ICS, MORGA_BIC)
values ('DIST55', '55', null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null);

insert into miworganization (MORGA_SOURCE, MORGA_REFORGA, MORGA_LIBELLE, MORGA_POSTECOMPTABLE, MORGA_NNE, MORGA_CENTRE, MORGA_DOCUMENT, MORGA_LOPFMT, MORGA_BANQUE, MORGA_NUMCOMPTE, MORGA_FLUX, MORGA_NNE_REMBOURS, MORGA_LIGNEOPTIQUE, MORGA_DIVERS, MORGA_RMH, MORGA_BANKFMT, MORGA_ICS, MORGA_BIC)
values ('DIST56', '56', null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null);

insert into miworganization (MORGA_SOURCE, MORGA_REFORGA, MORGA_LIBELLE, MORGA_POSTECOMPTABLE, MORGA_NNE, MORGA_CENTRE, MORGA_DOCUMENT, MORGA_LOPFMT, MORGA_BANQUE, MORGA_NUMCOMPTE, MORGA_FLUX, MORGA_NNE_REMBOURS, MORGA_LIGNEOPTIQUE, MORGA_DIVERS, MORGA_RMH, MORGA_BANKFMT, MORGA_ICS, MORGA_BIC)
values ('DIST57', '57', null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null);

insert into miworganization (MORGA_SOURCE, MORGA_REFORGA, MORGA_LIBELLE, MORGA_POSTECOMPTABLE, MORGA_NNE, MORGA_CENTRE, MORGA_DOCUMENT, MORGA_LOPFMT, MORGA_BANQUE, MORGA_NUMCOMPTE, MORGA_FLUX, MORGA_NNE_REMBOURS, MORGA_LIGNEOPTIQUE, MORGA_DIVERS, MORGA_RMH, MORGA_BANKFMT, MORGA_ICS, MORGA_BIC)
values ('DIST58', '58', null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null);

insert into miworganization (MORGA_SOURCE, MORGA_REFORGA, MORGA_LIBELLE, MORGA_POSTECOMPTABLE, MORGA_NNE, MORGA_CENTRE, MORGA_DOCUMENT, MORGA_LOPFMT, MORGA_BANQUE, MORGA_NUMCOMPTE, MORGA_FLUX, MORGA_NNE_REMBOURS, MORGA_LIGNEOPTIQUE, MORGA_DIVERS, MORGA_RMH, MORGA_BANKFMT, MORGA_ICS, MORGA_BIC)
values ('DIST59', '59', null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null);

insert into miworganization (MORGA_SOURCE, MORGA_REFORGA, MORGA_LIBELLE, MORGA_POSTECOMPTABLE, MORGA_NNE, MORGA_CENTRE, MORGA_DOCUMENT, MORGA_LOPFMT, MORGA_BANQUE, MORGA_NUMCOMPTE, MORGA_FLUX, MORGA_NNE_REMBOURS, MORGA_LIGNEOPTIQUE, MORGA_DIVERS, MORGA_RMH, MORGA_BANKFMT, MORGA_ICS, MORGA_BIC)
values ('DIST60', '60', null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null);

insert into miworganization (MORGA_SOURCE, MORGA_REFORGA, MORGA_LIBELLE, MORGA_POSTECOMPTABLE, MORGA_NNE, MORGA_CENTRE, MORGA_DOCUMENT, MORGA_LOPFMT, MORGA_BANQUE, MORGA_NUMCOMPTE, MORGA_FLUX, MORGA_NNE_REMBOURS, MORGA_LIGNEOPTIQUE, MORGA_DIVERS, MORGA_RMH, MORGA_BANKFMT, MORGA_ICS, MORGA_BIC)
values ('DIST61', '61', null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null);

insert into miworganization (MORGA_SOURCE, MORGA_REFORGA, MORGA_LIBELLE, MORGA_POSTECOMPTABLE, MORGA_NNE, MORGA_CENTRE, MORGA_DOCUMENT, MORGA_LOPFMT, MORGA_BANQUE, MORGA_NUMCOMPTE, MORGA_FLUX, MORGA_NNE_REMBOURS, MORGA_LIGNEOPTIQUE, MORGA_DIVERS, MORGA_RMH, MORGA_BANKFMT, MORGA_ICS, MORGA_BIC)
values ('DIST63', '63', null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null);

prompt Done.
