--update WFCONTACT w set w.par_id =null where w.par_id is not null;
update WFCONTACT w set w.sag_id =null where w.sag_id is not null;
update WFCONTACT w set w.spt_id =null where w.spt_id is not null;
update WFLISTITC t set t.par_id=null;
update WFLISTAGE w set w.age_id=null;
update WFMETAPE w set w.age_id = null;
COMMIT;

alter table AGRCGHBILL disable constraint FK_AGRCGHBILL_BILLINE;
alter table PAYCASHBLI disable constraint FK_PAYCASHBLI_BLI;
alter table CNVLINEVOUCHER disable constraint FK_CNVLINEVOUCHER_BIL;
alter table GENBILL disable constraint FK_GENBILL_DECOMPTE;
alter table GENBILLINE disable constraint FK_GENBILLINE_REVERSEBLI;
alter table GENBILLINE disable constraint FK_GENBILLINE_REVERSEBLIDEC;
alter table PAYCASHBLI disable constraint FK_PAYCASHBLI_REVERSEBLI;
alter table PAYCASHBLI disable constraint FK_PAYCASHBLI_REVERSEBLIDEC;
alter table WORBILL disable constraint FK_WORBILL_GENBILL;
alter table AGRMONTHPAY disable constraint FK_AGRMONTHPAY_DEB;
alter table GENBILL disable constraint FK_GENBILL_DEB;
alter table GENCONTEST disable constraint FK_GENCONTEST_DEB;
alter table GENDEBIMP disable constraint FK_GENDEBIMP_DEB;
alter table GENDEBREC disable constraint FK_GENDEBREC_DEB;
alter table GENLETTDEBTDETAIL disable constraint FK_GENLETTDEBTDETAIL_DEB;
alter table GENPASDEB disable constraint FK_GENPADDEB_DEB;
alter table GENPAYSCHEDBR disable constraint FK_GENPAYSCHEDBR_DEB;
alter table GENTMPEDDEBT disable constraint FK_GENTMPEDDEBT_DEB;
alter table GENTMPSEPA disable constraint FK_GENTMPSEPA_DEB;
alter table PAYCASHDEBT disable constraint FK_PAYCASHDEBT_DEB;
alter table AGRMONTHPAYSCHED disable constraint FK_AGRMONTHPAYSCHED_BIL;
alter table AGRMONTHPAYSCHED disable constraint FK_AGRMONTHPAYSCHED_BIL_CANCEL;
alter table GENBILL disable constraint FK_GENBILL_BIL;
alter table GENBILL disable constraint FK_GENBILL_BIL_ID;
alter table GENBILL disable constraint FK_GENBILL_CANCEL;
alter table GENBILLINE disable constraint FK_GENBILLINE_BIL;
alter table GENRUNDETAIL disable constraint FK_GENRUNDETAIL_BILL;
alter table TECREADITEBILL disable constraint FK_TECREADITEBILL_BIL;
alter table AGRMONTHPAYSCHED disable constraint FK_AGRMONTHPAYSCHED_CSH;
alter table PAYCASHIMP disable constraint FK_PAYCASHIMP_CSH;
alter table PAYCASHING disable constraint FK_PAYCASHING_REJET;
alter table GENPARTYPARTY disable constraint FK_GENPARTYPARTY_PARENT;

delete from WFTMODFOLDER;
commit;	
delete from AGRADDDETAIL;
commit;
delete from AGRADDENDUM;
commit;
delete from AGRAVGCONSUM;
commit;
truncate table AGRBILL;  
commit;
truncate table AGRBILLINGITEM;  
commit;
delete from AGRCGHBILL;  
commit; 
delete from AGRCUSTAGRCONTACT;  
commit;
delete from AGRCUSTOMERAGR;  
commit;
delete from AGRHSAGOFR;  
commit;
delete from AGRMONTHPAY;  
commit;
delete from AGRMONTHPAYSCHED;  
commit;
delete from AGRPAYOR;  
commit;
delete from AGRPLANNINGAGR;  
commit;
delete from AGRSAGACO;  
commit;
delete from AGRSAGBUN;  
commit;
delete from AGRSERVICEAGR;  
commit;
delete from AGRSETTLEMENT;  
commit;
delete from AGRSUBSCRIPTION;  
commit;
delete from AGRSUBSCRIPTIONVALUE;  
commit;
delete from AGRTMPITEBILL;  
commit;
delete from AGRTMPTARIF;  
commit;
delete from AGRTMPWORBILL;  
commit;
delete from BILTMPBILLINGITEM;  
commit;
delete from BILTMPCONSUMACO;  
commit;
delete from BILTMPLASTBILL;  
commit;
delete from BILTMPNEXTMRD;  
commit;
delete from BILTMPSAG;  
commit;
delete from BILTMPSUBSCRIPTIONVALUE;  
commit;
delete from BILTMPTARIF;  
commit;
delete from FILTRE_SAV_AGRCONTRATTYPE;  
commit;
delete from FILTRE_SAV_GENAGENT;  
commit;
delete from FILTRE_SAV_GENPARTY;  
commit;
delete from FILTRE_SAV_WFMCONTACT;  
commit;
delete from FILTRE_SAV_WFMDOSSIER;  
commit;
delete from DEFALCROUTE;
commit;
delete from DEFALCROUTEHIST;
commit;
delete from GENACCOUNT where aco_status != 1 and par_id not in (select org_id from genorganization);  
commit;
delete from GENACTIVERECO;  
commit;
delete from GENACTIVERECODETAIL;
commit;
delete from GENACTIVITY;
commit;
delete from GENADRESS where adr_id not in (select adr_id from genparty where par_id in (select org_id from genorganization) union select adr_id from genagent);  
commit;
delete from GENANOMALY;  
commit;
delete from GENAVGCONSUM;  
commit;
delete from GENBANKPARTY where bap_id not in (select * from (select NVL(o.bap_credit_id,o.bap_debit_id) bap_id
 from genorganization o union select NVL(o.bap_debit_id,o.bap_credit_id) bap_id
  from genorganization o)
  where bap_id is not null); 
commit;
truncate table GENBILLINE;  
commit;
delete from GENBILL;   
commit;
delete from GENBUNDLE;  
commit;
delete from GENCAD;  
commit;
delete from GENCADPRESPT;  
commit;
delete from GENCONTEST;  
commit;
delete from GENCTRANOMALY;  
commit;
delete from GENDATADYN;  
commit;
delete from GENDATADYNDFT;  
commit;
delete from GENDEBIMP;  
commit;
delete from GENDEBREC;  
commit;
delete from GENPAYSCHEDBRDETAIL;
commit;
delete from GENPAYSCHEDBR;
commit;
truncate table GENDEBT;  
commit;
truncate table GENDEBTDISC;
commit;
delete from GENDIVSPT;  
commit;
delete from GENDOCISSUE;  
commit;
delete from GENFILE;  
commit;
delete from GENHCTRL;  
commit;
delete from GENHIMPCTT;  
commit;
delete from GENHTREATMENT;  
commit;
delete from GENHTREATPARAM;  
commit;
delete from GENLETTDEBT;  
commit;
delete from GENLETTDEBTDETAIL;  
commit;
delete from GENNEWS;  
commit;
delete from GENPAYSCHEDDETAIL;
commit;
delete from GENPAYSCHEDBRDETAIL;
commit;
delete from GENPAYSCHEDBR;
commit;
delete from GENPAYSCHED;
commit;
delete from GENPASDEB;
commit;
delete from GENPARTY where par_id not in(select org_id from genorganization 
                                        union 
										select 1 from dual 
										union 
										select par.par_id
										from  genparty par,
											  genrefext rex, 
											  genrefextdft ref,
											  genvocword vow
										where par.par_id = rex.rex_idorig 
										and   ref.ref_id = rex.rex_id
										and   ref.ref_table = 'GENPARTY'
										and   ref.ref_column = 'PAR_REFE'
										and   ref.vow_soft = vow.vow_id 
										and   vow.vow_code in ('RHUI','REXP'));  
commit;
delete from GENPARTYPARTY where par_parent_id not in(select par_id from genparty);  
commit;
delete from GENPASDEB;  
commit;
delete from GENPAYSCHED;  
commit;
delete from GENPAYSCHEDDETAIL;  
commit;
delete from GENPROJECT;
commit;
delete from GENPROVIDER;
commit;
delete from GENREFEXT;  
commit;
delete from GENRUN;  
commit;
delete from GENRUNAGR;  
commit;
delete from GENRUNDETAIL;  
commit;
delete from GENRUNDVT;  
commit;
delete from GENRUNGRF;   
commit;
delete from GENSOCIALSTATUS;  
commit; 
delete from GENSTREET where str_id != 0;  
commit; 
delete from GENTMPBILLINE;  
commit;
delete from GENTMPEDDEBT;  
commit;
delete from GENTMPHGED;  
commit;
delete from GENTMPITEMTARIF;  
commit;
delete from GENTMPSEPA;  
commit; 
delete from GENWORKSTATE;  
commit;
delete from LIGNE_PLGREL;
commit;
delete from LIGNE_PLGRELHIST;
commit;
delete from PAYCASHBLI;  
commit;
delete from PAYCASHDEBT;  
commit;
delete from PAYCASHDESKMOVE;  
commit;
delete from PAYCASHDESKSESSION WHERE CSS_ID not in (select css_id from paycashdesk where cah_code = '01');--  CAISSE
commit;
delete from PAYCASHIMP;  
commit;
delete from PAYCASHING;  
commit;
delete from PAYJOURNAL;  
commit;
delete from PAYSLIP;  
commit;
delete from PLGREL;
commit;
delete from PLGRELHIST;
commit;
delete from TECCONNECTION;  
commit;
delete from TECCONNHIER;
commit;
delete from TECDEVICE;
commit;
delete from TECEQUIPMENT;  
commit;
delete from TECEQUMODEL;  
commit;
delete from TECHCONSPT;  
commit;
delete from TECHEQUCOM;  
commit;
delete from TECHEQUIPMENT;  
commit;
delete from TECHEQUMTRCFG;  
commit;
delete from TECIMPORTDETAIL;  
commit;
delete from TECIMPORTMODEL;  
commit;
delete from TECMETER;  
commit;
delete from TECMTRELEC;  
commit;
delete from TECMTRGAS;  
commit;
delete from TECMTRMEASURE;  
commit;
delete from TECMTRMEASURECHARGE;  
commit;
truncate table TECMTRREAD;  
commit;
delete from TECMTRWATER;  
commit;
delete from TECMTRWASTE;
commit;
delete from TECPLGREL;
commit;
delete from TECPLGRELHIST;
commit;
delete from TECPREINFOETUDE;
commit;
delete from TECPREMISE;  
commit;
delete from TECPREMISEHIER;  
commit;
delete from TECPREREJECT;  
commit;
delete from tecpreinfoetude;
commit;
delete from TECPRESPTCONTACT;  
commit;
delete from TECREADITEBILL;  
commit;
delete from TECROUCUT;  
commit;
delete from TECROUFLD;  
commit;
delete from TECROUSTR;  
commit;
delete from TECROUTE;  
commit;
delete from TECROUTEDEFALC;  
commit;
delete from TECROUTEDEFALCDETAIL;  
commit;
delete from TECROUTELOAD;  
commit;
delete from TECROUTELOADDETAIL;  
commit;
delete from TECROUTEPLAN;  
commit;
delete from TECROUTEUNLOAD;  
commit;
delete from TECSERVICEPOINT;  
commit;
delete from TECSPSTATUS;  
commit;
delete from TECSPTELECTRIC;  
commit;
delete from TECSPTGAS;  
commit;
delete from TECSPTHIER;  
commit;
delete from TECSPTORG;  
commit;
delete from TECSPTREJECT;  
commit;
delete from TECSPTWASTE;  
commit;
delete from TECSPTWATER;  
commit;
delete from WFCONDOS where con_id in (select con_id from wfcontact where con_mcon_id is not null);
commit;
delete from WFCONTACT where con_mcon_id is not null;
commit;
delete from WFDEPENDANCEFOLDE;
commit;
delete from WFDOCTAG;
commit;
delete from WFDOCUMENTLIE;
commit;
delete from WFDOSSIER where dos_mdos_id is not null;
commit;
delete from WFETAPE where dos_id in (select dos_id from WFDOSSIER where dos_mdos_id is not null);
commit;
delete from WFFIELD;
commit;
delete from WFFIELDARCH;
commit;
delete from WFFOLDER;
commit;
delete from WFFVALID;
commit;
delete from WFFVALIDARCH;
commit;
delete from WFHPROCESS where dos_id in (select dos_id from WFDOSSIER where dos_mdos_id is not null);
commit;
delete from WFLIST where lst_id in (select lag_id from wfcontact where con_mcon_id is not null
                                    union  
									select lit_id from wfcontact where con_mcon_id is not null
									union
									select lob_id from wfcontact where con_mcon_id is not null
									union
									select lag_id from wfdossier where dos_mdos_id is not null
                                    union  
									select lit_id from wfdossier where dos_mdos_id is not null
									union
									select lob_id from wfdossier where dos_mdos_id is not null);
commit;
delete from WFLISTAGE where lag_id in (select lag_id from wfcontact where con_mcon_id is not null
									   union
									   select lag_id from wfdossier where dos_mdos_id is not null);
commit;
delete from WFLISTITC where lit_id in (select lit_id from wfcontact where con_mcon_id is not null
									   union
									   select lit_id from wfdossier where dos_mdos_id is not null);
commit;
delete from WFLISTOBJECT where lob_id in (select lob_id from wfcontact where con_mcon_id is not null
									      union
									      select lob_id from wfdossier where dos_mdos_id is not null);
commit;
delete from WFLOTDEDEPENDANCE;
commit;
delete from WFMOTIF;
commit;
delete from WFSCREAN;
commit;
delete from WFSCREANARCH;
commit;
delete from WFSTEP;
commit;
delete from WFTAFFECTATION;
commit;
delete from WFTASSISTANT;
commit;
delete from WFTCONDITION;
commit;
delete from WFTCOURRIER;
commit;
delete from WFTDEMANDE;
commit;
delete from WFTIMPRESSION;
commit;
delete from WFTINTERVENTION;
commit;
delete from WFTITERATIF;
commit;
delete from WFTOBJETMETIER;
commit;
delete from WFTROLLBACK;
commit;
delete from WFTTRAITEMENT;
commit;
delete from WFTTRAVAUX;
commit;
delete from WORASSIGNMENT;  
commit;
delete from WORBILL;  
commit;
delete from WORBILLINTERV;
commit;
delete from WORLINEQUOTATION;  
commit;
delete from WORQUOTATION;  
commit;
delete from WORREPORTORDER;   
commit;
delete from WORTEMPJER;  
commit;
delete from WORWOPLAN;
commit;
delete from WORWORKORDER;  
commit;
delete from WORWORKSHEET;  
commit;
delete from WORWORKSHEETITEM;  
commit;
alter table AGRCGHBILL enable constraint FK_AGRCGHBILL_BILLINE;
alter table PAYCASHBLI enable constraint FK_PAYCASHBLI_BLI;
alter table CNVLINEVOUCHER enable constraint FK_CNVLINEVOUCHER_BIL;
alter table GENBILL enable constraint FK_GENBILL_DECOMPTE;
alter table GENBILLINE enable constraint FK_GENBILLINE_REVERSEBLI;
alter table GENBILLINE enable constraint FK_GENBILLINE_REVERSEBLIDEC;
alter table PAYCASHBLI enable constraint FK_PAYCASHBLI_REVERSEBLI;
alter table PAYCASHBLI enable constraint FK_PAYCASHBLI_REVERSEBLIDEC;
alter table WORBILL enable constraint FK_WORBILL_GENBILL;
alter table AGRMONTHPAY enable constraint FK_AGRMONTHPAY_DEB;
alter table GENBILL enable constraint FK_GENBILL_DEB;
alter table GENCONTEST enable constraint FK_GENCONTEST_DEB;
alter table GENDEBIMP enable constraint FK_GENDEBIMP_DEB;
alter table GENDEBREC enable constraint FK_GENDEBREC_DEB;
alter table GENLETTDEBTDETAIL enable constraint FK_GENLETTDEBTDETAIL_DEB;
alter table GENPASDEB enable constraint FK_GENPADDEB_DEB;
alter table GENPAYSCHEDBR enable constraint FK_GENPAYSCHEDBR_DEB;
alter table GENTMPEDDEBT enable constraint FK_GENTMPEDDEBT_DEB;
alter table GENTMPSEPA enable constraint FK_GENTMPSEPA_DEB;
alter table PAYCASHDEBT enable constraint FK_PAYCASHDEBT_DEB;
alter table AGRMONTHPAYSCHED enable constraint FK_AGRMONTHPAYSCHED_BIL;
alter table AGRMONTHPAYSCHED enable constraint FK_AGRMONTHPAYSCHED_BIL_CANCEL;
alter table GENBILL enable constraint FK_GENBILL_BIL;
alter table GENBILL enable constraint FK_GENBILL_BIL_ID;
alter table GENBILL enable constraint FK_GENBILL_CANCEL;
alter table GENBILLINE enable constraint FK_GENBILLINE_BIL;
alter table GENRUNDETAIL enable constraint FK_GENRUNDETAIL_BILL;
alter table TECREADITEBILL enable constraint FK_TECREADITEBILL_BIL;
alter table AGRMONTHPAYSCHED enable constraint FK_AGRMONTHPAYSCHED_CSH;
alter table PAYCASHIMP enable constraint FK_PAYCASHIMP_CSH;
alter table PAYCASHING enable constraint FK_PAYCASHING_REJET;
alter table GENPARTYPARTY enable constraint FK_GENPARTYPARTY_PARENT;
delete from GENADRESS w where w.adr_id not in (0,98772,100158,100167,157900);
delete from GENSTREET w where str_id not in (select str_id from genadress);



 