create table prob_mig_client(obj_refe varchar2(400),code_except varchar2(400),message_except varchar2(400),pk_etape varchar2(400),date_except date);
create table prob_mig_pdl(obj_refe varchar2(400),code_except varchar2(400),message_except varchar2(400),pk_etape varchar2(400),date_except date);
create table prob_mig_contrat(obj_refe varchar2(400),code_except varchar2(400),message_except varchar2(400),pk_etape varchar2(400),date_except date);
create table prob_mig_releve(obj_refe varchar2(400),code_except varchar2(400),message_except varchar2(400),pk_etape varchar2(400),date_except date);
create table prob_mig_facture(obj_refe varchar2(400),code_except varchar2(400),message_except varchar2(400),pk_etape varchar2(400),date_except date);
create table prob_mig_relevet(obj_refe varchar2(400),code_except varchar2(400),message_except varchar2(400),pk_etape varchar2(400),date_except date);
create table prob_mig_b1(obj_refe varchar2(400),code_except varchar2(400),message_except varchar2(400),pk_etape varchar2(400),date_except date);
create table prob_mig_b2(obj_refe varchar2(400),code_except varchar2(400),message_except varchar2(400),pk_etape varchar2(400),date_except date);
create table prob_mig_relevegc(obj_refe varchar2(400),code_except varchar2(400),message_except varchar2(400),pk_etape varchar2(400),date_except date);
create table prob_mig_dossier(obj_refe varchar2(400),code_except varchar2(400),message_except varchar2(400),pk_etape varchar2(400),date_except date);

alter table genstreet modify str_name varchar2(400);
alter table genstreet modify str_namek varchar2(400);
alter table genstreet modify str_namer varchar2(400);

alter table client add par_id number(10);
alter table branchement add spt_id number(10);
alter table branchement add sag_id number(10);
alter table branchement add mtc_id number(10);
alter table branchement add equ_id number(10);
alter table branchement add adr_id number(10);
alter table branchement add par_id number(10);
alter table branchement add aco_id number(10);
alter table branchement add org_id number(10);


alter table src_fiche_releve add mrd_id number(10);
alter table relevet add mrd_id number(10);
alter table src_facture_as400 add bil_id number(10);
alter table src_facture_as400 add deb_id number(10);
alter table src_facture_as400 add mrd_id number(10);
alter table src_facture add bil_id number(10);
alter table src_facture add deb_id number(10);
alter table src_impayees  add bil_id number(10);
alter table src_impayees  add deb_id number(10);
alter table src_clients add par_id number(10);
alter table anomalie  add deb_id number(10);
alter table anomalie_travaux  add deb_id number(10);
alter table relevegc add mrd_id number(10);
alter table src_b1 add bil_id number(10);
alter table src_b1 add deb_id number(10);
alter table src_b2 add bil_id number(10);
alter table src_b2 add deb_id number(10);
alter table src_impayees add deb_id number(10);
alter table src_compte_attente add deb_id number(10);
alter table src_ano_eau_as400 add deb_id number(10);
alter table src_ano_trv_as400 add deb_id number(10);
alter table src_fac_annule add deb_id number(10);
alter table src_facture_as400_4 add bil_id number(10);
alter table src_facture_as400_4 add deb_id number(10);
alter table src_facture_as400_4 add mrd_id number(10);
alter table src_facture_as400_5 add bil_id number(10);
alter table src_facture_as400_5 add deb_id number(10);
alter table src_facture_as400_5 add mrd_id number(10);
alter table src_impayees_2 add deb_id number(10);
alter table src_impayees_2 add deb_id_41 number(10);
alter table demande_ds add dos_id number(10);
alter table src_facture_as400_7 add bil_id_41 number(10);
alter table src_facture_as400_7 add deb_id_41 number(10);
alter table src_facture_as400_7 add mrd_id_41 number(10);


update client set par_id = null where par_id is not null;
update branchement set sag_id = null, spt_id = null where spt_id is not null;
update src_fiche_releve set mrd_id = null;
update src_relevet set mrd_id = null;
update src_facture_as400 set bil_id = null,deb_id=null;
update src_facture_as400 set mrd_id=null;
update src_facture set bil_id = null,deb_id=null;
update src_impayee set bil_id=null,deb_id=null;