----------------------------------------------
----SRV-MIG1--------12*****	33	22	53	57	
----------------------------------------------
create user district33  identified by district33;
grant dba to district33;

create user district22  identified by district22;
grant dba to district22;

create user district53  identified by district53;
grant dba to district53;

create user district57  identified by district57;
grant dba to district57;

----------------------------------------------
----SRV-MIG2--------13****	44	45	60	36	
----------------------------------------------

create user district44  identified by district44;
grant dba to district44;

create user district45  identified by district45;
grant dba to district45;

create user district60  identified by district60;
grant dba to district60;

create user district36  identified by district36;
grant dba to district36;

----------------------------------------------
----SRV-MIG3--------14*****	25	42	28	21	
----------------------------------------------

create user district25  identified by district25;
grant dba to district25;

create user district42 identified by district45;
grant dba to district42;

create user district28  identified by district28;
grant dba to district28;

create user district21  identified by district21;
grant dba to district21;

----------------------------------------------
----SRV-MIG4--------15*****	54	05	14	13	
----------------------------------------------

create user district54  identified by district54;
grant dba to district54;

create user district05 identified by district05;
grant dba to district05;

create user district14  identified by district14;
grant dba to district14;

create user district13  identified by district13;
grant dba to district13;

----------------------------------------------
---SRV-MIG5--------16*****	17	56	63	15	52
----------------------------------------------

create user district17  identified by district17;
grant dba to district17;

create user district56 identified by district56;
grant dba to district56;
 
create user district63  identified by district63;
grant dba to district63;

create user district15 identified by district15;
grant dba to district15;

create user district52 identified by district52;
grant dba to district52;

----------------------------------------------
---SRV-MIG6--------17*****	16	32	08	31	58
----------------------------------------------

create user district16  identified by district16;
grant dba to district16;

create user district32 identified by district32;
grant dba to district32;

create user district08 identified by district08;
grant dba to district08;
 
create user district31  identified by district31;
grant dba to district31;

create user district58 identified by district58;
grant dba to district58;

----------------------------------------------
---SRV-MIG7--------18*****	37	03	01	46	61
----------------------------------------------

create user district37  identified by district37;
grant dba to district37;

create user district03  identified by district03;
grant dba to district03;

create user district01 identified by district01;
grant dba to district01;
 
create user district46  identified by district46;
grant dba to district46;

create user district61 identified by district61;
grant dba to district61;

----------------------------------------------
---SRV-MIG8--------19*****	06	04	07	29	59
----------------------------------------------

create user district06  identified by district06;
grant dba to district06;

create user district04  identified by district04;
grant dba to district04;

create user district07 identified by district07;
grant dba to district07;
  
create user district29  identified by district29;
grant dba to district29;

create user district59 identified by district59;
grant dba to district59;

----------------------------------------------
---SRV-MIG9--------20*****	26	20	34	24	49
----------------------------------------------

create user district26  identified by district26;
grant dba to district26;

create user district20  identified by district20;
grant dba to district20;

create user district34 identified by district34;
grant dba to district34;
 
create user district24  identified by district24;
grant dba to district24;

create user district49 identified by district49;
grant dba to district49;

----------------------------------------------
---SRV-MIG10--------21*****	09	48	19	27	55
----------------------------------------------

create user district09  identified by district09;
grant dba to district09;

create user district48  identified by district48;
grant dba to district48;

create user district19 identified by district19;
grant dba to district19;
 
create user district27  identified by district27;
grant dba to district27;

create user district55 identified by district55;
grant dba to district55;