---------------------table verif_cal_migration-------------
CREATE TABLE  VERIF_CALC_MIGRATION 
(DIV_CODE VARCHAR2(20 BYTE), 
DIV_NAME VARCHAR2(200 BYTE), 
DVT_ID NUMBER(*,0), 
PDL NUMBER(*,0), 
BRANCHEMENT NUMBER(*,0), 
DEF_SOURCE_PROD NUMBER(*,0), 
SITE NUMBER(*,0), 
CONTACT_SITE_PDL NUMBER(*,0), 
ABONNEMENT NUMBER(*,0), 
CONTACT_ABONNEMENT NUMBER(*,0), 
PAYEUR NUMBER(*,0), 
ADRESSE_FACTURATION NUMBER(*,0), 
ADRESSE NUMBER(*,0), 
HISTORIQUE_POSE_COMPTEUR NUMBER(*,0), 
COMPTEUR NUMBER(*,0), 
HISTOR_PROFIL_FACTURATION NUMBER(*,0), 
ETAT_PDL NUMBER(*,0), 
PLANNING_FACTURATION NUMBER(*,0), 
SECTORISATION NUMBER(*,0), 
AFFICTATION_PDL_ORGANISATION NUMBER(*,0), 
MODILITE_DE_PAIMENT NUMBER(*,0), 
COMPTE_ABONNEMENT NUMBER(*,0), 
VERIF_CONTACT_SITE_PDL VARCHAR2(20 BYTE), 
VERIF_CONTACT_ABONNEMENT VARCHAR2(20 BYTE), 
VERIF VARCHAR2(20 BYTE), 
FACT_AS400_S VARCHAR2(100 BYTE), 
FACT_AS400_P VARCHAR2(100 BYTE), 
FACT_AS400GC_S VARCHAR2(100 BYTE), 
FACT_AS400GC_P VARCHAR2(100 BYTE), 
FACT_VERS_S VARCHAR2(100 BYTE), 
FACT_VERS_P VARCHAR2(100 BYTE), 
F_RELEVE_S VARCHAR2(20 BYTE), 
F_RELEVE_P VARCHAR2(20 BYTE), 
RELEVET_S VARCHAR2(20 BYTE), 
RELEVET_P VARCHAR2(20 BYTE), 
RELEVEGC_S VARCHAR2(20 BYTE), 
RELEVEGC_P VARCHAR2(20 BYTE), 
IMPAYEES_PART_S VARCHAR2(20 BYTE), 
IMPAYEES_PART_P VARCHAR2(20 BYTE), 
IMPAYEES_GC_S VARCHAR2(20 BYTE), 
IMPAYEES_GC_P VARCHAR2(20 BYTE)
);
  
------------------table test_migration ----------------   
CREATE TABLE TEST_MIGRATION 
(REFERENCE VARCHAR2(200 BYTE), 
TYPE VARCHAR2(200 BYTE), 
CODE_DIST VARCHAR2(20 BYTE)
);

CREATE INDEX pivot.TEST_MIGRATION_INDEX1 
ON pivot.TEST_MIGRATION (SUBSTR(REFERENCE,1,8), TYPE, CODE_DIST);
